# Generated by Django 3.1.6 on 2021-02-05 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_no', models.IntegerField()),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='patientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.IntegerField()),
                ('ibm', models.IntegerField()),
                ('glucose', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('hemoglobin', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientInfo.patient')),
            ],
        ),
    ]
